#!/bin/bash

set -eu

# This hook will check for your desired pattern in the code and let you know
# when switching branch if there's something you need to fix.

pattern="(PROJECT1-|PROJECT2-)"
current_branch="$(git branch-name)"
to_find="$(echo "$current_branch" | gsed -E "s/.*(${pattern}[^_-]*).*/\1/gI")"

# Ensure the current branch even contains our pattern.
shopt -s nocasematch
if ! [[ "$current_branch" =~ $pattern ]]; then
    exit 0
fi

output=$(grep -Erin --exclude-dir={node_modules,.git} "$to_find" ./*)

if [ -n "$output" ]; then
    echo "Found TODO's marked pattern from your branch!"
    echo ""
    echo "$output"
fi
